baseURL = 'https://stranaimir2023.sakharov.world/'
languageCode = 'ru'
title = 'О стране и мире: Российские реалии 2023'
theme = 'conference2023_theme'
publishDir = 'docs'
relativeURLS = true

[params]
  description = 'Международная конференция «Страна и мир» посвящена российской агрессии против Украины и тому, как эта война меняет Россию. Мы будем говорить о трансформации политического режима и его идеологии, состоянии российского общества, репрессиях и военных преступлениях, новой волне эмиграции, международной политике и экономике.'
  images = ['opengraph-ru.png']
  title = 'О стране и мире: Российские реалии 2023'

[module]
    [[module.mounts]]
        source = 'node_modules/bootstrap/dist/js/bootstrap.bundle.min.js'
        target = 'assets/js/bootstrap.bundle.min.js'